### ISSUE TITLE
Vue generated scripts getting blocked

### ISSUE THREAD

**Issue by TheOluwafemi** [netlify/plugin-csp-nonce#52]
Hello, please can anyone help me with this? These 2 scripts `app.js` and `chunk-vendors.js` are getting blocked in production. 

<img width="1781" alt="Screenshot 2023-10-19 at 4 46 58 PM" src="https://github.com/netlify/plugin-csp-nonce/assets/29064229/5b250a2a-7524-4ced-babf-3fe532b08d11">

Here is the configuration in my netlify.toml

```
.
.
[[plugins]]
  package = "@netlify/plugin-csp-nonce"
    [plugins.inputs]
      reportOnly = false
      unsafeEval = true
.
.
```

**Comment by jasonbarry** [comment]
@TheOluwafemi hi there, do you have a public URL that I could inspect?

**Comment by TheOluwafemi** [comment]
> @TheOluwafemi hi there, do you have a public URL that I could inspect?

Here @jasonbarry 
https://deploy-preview-2106--yellowcard-webapp.netlify.app

**Comment by jasonbarry** [comment]
Thanks @TheOluwafemi. It appears that there is some clientside logic in your code that is setting the nonce attribute on script tags to `Lmmd6Yf1HphgVfdxhTC8qlV0qYFWNJTa1` on every load. You shouldn't need any static value here injected clientside; rather, the build plugin deploys an edge function which generates a unique value on every request. You can test by disabling JavaScript and loading the page -- notice that the nonce values in the HTML match the value in the Content-Security-Policy header.

**Comment by TheOluwafemi** [comment]
Thanks @jasonbarry and you are right, I was running a test to see if the nonce attributes are truly dynamic, but, I have removed that piece of code now. However, the issue still persists those 2 scripts added by the vue framework are still getting blocked.

**Comment by jasonbarry** [comment]
Hmm interesting indeed, I'm seeing it now in Chrome. I'm not able to reproduce it in Firefox or Safari, which is strange. I'm not quite sure what's different with those two scripts, as the other scripts on the same page seem to execute with the same nonce value. Thanks for reporting, I'll think about this some more

**Comment by TheOluwafemi** [comment]
Hello @jasonbarry please were you able to investigate further? Do you have any updates?

**Comment by jasonbarry** [comment]
@TheOluwafemi this might be something specific with your project -- I was able to deploy [a basic Vue app here](https://frolicking-alpaca-6e0635.netlify.app/) ([see code](https://github.com/jasonbarry/vue-project)) and the CSP doesn't block scripts. Could you tell me more about the details / stack / dependencies of your project?

**Comment by TheOluwafemi** [comment]
Is it possible to modify the script-src added by the @netlify/plugin-csp-nonce? @jasonbarry

**Comment by jasonbarry** [comment]
@TheOluwafemi I've deployed a Vue 2 site at https://vue-2-example.netlify.app ([source](https://github.com/jasonbarry/vue-2-example)) that's built with webpack and uses your same config in the netlify.toml, and it's working as expected. I'm sorry, but the issue you are encountering must be something specific to your project/code. There isn't a reason why the edge function that transforms the script tags would only apply to some but not others.

**Comment by TheOluwafemi** [comment]
@jasonbarry thanks you for your help so far. After snooping around I found that those 2 scripts are prepped scripts and they are sort of duplicates, only they are not wrapped in <script> rather they are <link as='sript' ../> and I don't think the move captures this. I removed the preload scripts in the web pack config (Vue Config in this case) and the app works as expected now, so definitely that's what needs fixing.

**Comment by TheOluwafemi** [comment]
I just saw that you have a new release PR #59 that addresses this issue specifically. I am testing it out now. 

Also, is there a possibility of adding more custom policies like object-arc, base-uri etc. Can this feature be added?

**Comment by jasonbarry** [comment]
oh, gotcha! Yes, https://github.com/netlify/plugin-csp-nonce/pull/59 fixed the `<link rel="preload">` issue. 

> Also, is there a possibility of adding more custom policies like object-arc, base-uri etc. Can this feature be added?

Nope, there are no plans to add other directives -- this plugin is specifically for adding a nonce to the script-src directive. However, you can add whichever directives you'd like by using [Custom Headers](https://docs.netlify.com/routing/headers/). The script-src w/ nonce from this plugin will merge with any existing CSP from your site that you define either in the _headers file, netlify.toml, or an edge function.

**Comment by TheOluwafemi** [comment]
Thank you @jasonbarry this works now, the preload scripts are not getting blocked anymore and I have been able to extend the policy via custom headers. We can close this issue now, thanks once again for the prompt response and the PR merge!

**Comment by jasonbarry** [comment]
No prob, thanks for reporting!
