### ISSUE TITLE
link preload's don't have nonce's added.

### ISSUE THREAD

**Issue by stuckj** [netlify/plugin-csp-nonce#58]
I enabled the integration-csp in netlify to try out with our site. It works pretty well! Thanks for writing this! I did find one non-blocking issue though. The build from our site adds `<link rel="preload" as="script" ... />` statements for all the generated scripts in addition to the later `<script .../>` tags. All of the preloads generate CSP violations since they don't have the nonce's on them. However, the actual `<script ... />` tags load fine so the site actually loads ok. Our site is built with gatsby. Specifically, an older version (Gatsby v2). Not sure if this is something that isn't done in newer versions.

I think this can be pretty easily fixed with another condition to `HTMLRewriter` in `__csp-nonce.ts` to handle `link` where `rel` is `preload` and `as` is `script`. I'll see about doing a quick PR with the change.

**Comment by stuckj** [comment]
Sorry, no PR from me. I just wasted over an hour just trying to get a super simple edge function running locally based on https://docs.netlify.com/edge-functions/declarations/#declare-edge-functions-in-netlify-toml and netlify dev won't even run the hello example edge function locally. Maybe it's related to [this](https://github.com/netlify/cli/issues/4584) or [this](https://github.com/netlify/edge-functions-examples/issues/42).

So, rather than push you a PR with completely untested code I'm just going to punt unless I find more time at a later time. I'm guessing you guys can much more easily test a change to fix this than I can right now.

I think all that's needed is to change this:
```
  return new HTMLRewriter()
    .on("script", {
      element(element: HTMLElement) {
        element.setAttribute("nonce", nonce);
      },
    })
    .transform(response);
```

to this:
```
  return new HTMLRewriter()
    .on("script", {
      element(element: HTMLElement) {
        element.setAttribute("nonce", nonce);
      },
    })
    .on("link[rel=\"preload\"][as=\"script\"]", {
      element(element: HTMLElement) {
        element.setAttribute("nonce", nonce);
      },
    })
    .transform(response);
```

in `__csp-nonce.ts`.

That way both script tags and link tags (that have rel="preload" and as="script") get the nonce added.

**Comment by jasonbarry** [comment]
Thanks for reporting @stuckj, and sorry you couldn't verify locally! I've opened #59 and added a case in this repo's site, so that it could be tested in the corresponding [Deploy Preview](https://deploy-preview-59--csp-nonce.netlify.app). It works! I'll merge this in and release shortly.

**Comment by stuckj** [comment]
Thanks @jasonbarry! Do you know how I would update our site to use the new plugin code once it's released? Just re-push our site? Or, perhaps disable/re-enable the integration?

**Comment by jasonbarry** [comment]
@stuckj the integration repo consumes this plugin as a dependency, so once I update the integration, all you'd need to do is redeploy. I'll ping you again once complete, should be about 10-15 minutes or so.

**Comment by jasonbarry** [comment]
@stuckj could you try redeploying your site, and see if it picks up the latest integration version? thanks!

**Comment by stuckj** [comment]
@jasonbarry, that did it. Verified that I'm no longer getting CSP errors from the preloads. Thanks for the quick merge!
