### ISSUE TITLE
Remove backwards compatible csp rules

### ISSUE THREAD

**Issue by aar9nk** [netlify/plugin-csp-nonce#67]
I am creating a csp and attempting to use netlify headers to achieve it. I have a content-security-policy set out in a headers file and I am attempting to use plugin-csp-nonce. It seems this will merge the two together prioritising plugin-csp-nonce which is exactly what I am looking for, however I would prefer to not use the `http` and `https` and possibly not use the `self` attribute. 

I am looking to keep my own csp as the fallback, would you be open to an input param to remove the backwards compatibility? 

I have created a linked [PR](https://github.com/netlify/plugin-csp-nonce/pull/66) with my attempt at an addition, but I am open to different naming conventions or changes in logic.

If not, it's no big deal and I can fork this for my own use.

**Comment by jasonbarry** [comment]
Thanks for raising @aar9nk! `http:`, `https:`, and `self` are actually ignored when the `strict-dynamic` keyword is present. We only leave them there as a fallback for browsers that do not support `strict-dynamic`. See the `Dealing with Unsupported Browsers` section of https://content-security-policy.com/strict-dynamic/

**Comment by aar9nk** [comment]
All good, thanks for considering!
